scalar:
  defaults:
    BigDecimal: ${VARIABLE} = java.math.BigDecimal.ONE
    LocalDate: ${VARIABLE} = java.time.LocalDate.now()
    LocalDateTime: ${VARIABLE} = java.time.LocalDateTime.now()
    UUID: ${VARIABLE} = UUID.randomUUID()
    Date: ${VARIABLE} = new Date()
    URL: try {
          ${VARIABLE} = new URL("http://foo.graphql");
        } catch (java.net.MalformedURLException e)
        {}
  imports:
    BigDecimal: import java.math.BigDecimal;
    LocalDate: import java.time.LocalDate;
    LocalDateTime: import java.time.LocalDateTime;
    UUID: import java.util.UUID;
    Date: import java.util.Date;
    URL: import java.net.URL;
